### ISSUE TITLE
Can't download tahoma32.exe

### ISSUE THREAD

**Issue by Epowerj** [Unity3D-Wine-Support/Unity3D-on-Wine#63] opened 2015-07-21 03:56 UTC
I'm running unity3d.verb with winetricks and it can't seem to download tahome32.exe. I've made sure that my internet is fine, and even tried pinging the ip with no result. 

See output:

```
(trusty)epowerj@localhost:~$ winetricks -q "./unity3d.verb"
Executing w_do_call unity3d
Executing load_unity3d
Executing w_do_call tahoma
Executing load_tahoma
Downloading ftp://64.4.17.176/Softlib/MSLFILES/tahoma32.exe to /home/epowerj/.cache/winetricks/tahoma
--2015-07-20 23:46:49--  ftp://64.4.17.176/Softlib/MSLFILES/tahoma32.exe
           => 'tahoma32.exe'
Connecting to 64.4.17.176:21... failed: Connection timed out.
Retrying.

--2015-07-20 23:48:57--  ftp://64.4.17.176/Softlib/MSLFILES/tahoma32.exe
  (try: 2) => 'tahoma32.exe'
Connecting to 64.4.17.176:21... failed: Connection timed out.
Retrying.

--2015-07-20 23:51:06--  ftp://64.4.17.176/Softlib/MSLFILES/tahoma32.exe
  (try: 3) => 'tahoma32.exe'
Connecting to 64.4.17.176:21... 

```

**Comment by DoctorJellyface** [comment] 2015-07-23 18:53
Duplicate of #27. Either run `wget ftp://ftp.microsoft.com/Softlib/MSLFILES/tahoma32.exe && mv tahoma32.exe ~/.cache/winetricks/tahoma/` and run the script again, or update winetricks (see the last comment for a quick and easy one-liner).

**Closed by DoctorJellyface** 2015-07-23 18:53 UTC
Labels: duplicate
